services:
  db:
    container_name: db
    image: postgres:13.16
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: xpto
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  go:
    container_name: go-api
    image: tpalves/golang-gin-api:1.1
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  pgdata: {}